wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.2
    start_time: 1653945715
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 19
      4: 3.10.2
      5: 0.12.15
      8:
      - 5
batch_size:
  desc: null
  value: 14
device:
  desc: null
  value: cpu
dropout:
  desc: null
  value: 0.2955490803285648
epochs:
  desc: null
  value: 30
lr:
  desc: null
  value: 1.0e-06
momentum:
  desc: null
  value: 0.7220523964783008
