wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.2
    start_time: 1653945415
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      4: 3.10.2
      5: 0.12.15
      8:
      - 5
batch_size:
  desc: null
  value: 14
dropout:
  desc: null
  value: 0.23417730203900528
lr:
  desc: null
  value: 0.0001
momentum:
  desc: null
  value: 0.8598382618623116
